### ISSUE TITLE
Blocking optional dependency

### ISSUE THREAD

**Issue by Tux** [marioroy/mce-shared#2]
Let me start with expressing my thanks for making MCE::Shared work **without** IO::FDPass

But the dependency is still too hard
``` sh
$ perl Makefile.PL
## The IO::FDPass module is known to work on this platform.
## Thus, adding IO::FDPass to PREREQ for a better experience
## sharing MCE::Shared::{ Condvar, Handle, and Queue }.

Checking if your kit is complete...
Looks good
Warning: prerequisite IO::FDPass 1.2 not found.
Generating a Unix-style Makefile
Writing Makefile for MCE::Shared
Writing MYMETA.yml and MYMETA.json
```
Which causes the automated process to skip MCE::Shared, so it could try to use it, it may report it to be of any value for some, but it should not add it to the dependency list if it is not installed

**Comment by marioroy** [comment]
Setting an environment variable MCE_PREREQ_EXCLUDE_IO_FDPASS=1 excludes the IO::FDPass check during perl Makefile.PL.
