### ISSUE TITLE
Add GitHub Actions to have CI

### ISSUE THREAD

**Issue by szabgab** [marioroy/mce-shared#4]
I am using the CPAN Digger to locate recently release modules that don't have a CI system. As I can see [non of your modules](https://cpan-digger.perlmaven.com/author/MARIOROY) have a CI setup.

This project too could benefit from setting up a CI system to run the tests on every push and every pull-requests. I've written about this [here](https://perlmaven.com/github-actions).

If you are interested I'd be happy to send you PR to this and to your other CPAN modules.

**Comment by marioroy** [comment]
I will try to enable CI by following your example.

https://github.com/michal-josef-spacek/Date-ICal/pull/2/commits/2f65d3f04cad6942867e8fd740d4166b81953bd8

**Comment by szabgab** [comment]
Great. Let me know if you need any help.

**Comment by marioroy** [comment]
Thank you! My GitHub repositories MCE, MCE::Shared, and Mutex have CI enabled. I added a comment to the ci.yml file to not test Perl 5.24 on windows-latest due to missing dmake. Perl 5.30 uses gmake.

**Comment by szabgab** [comment]
Nice!

**Comment by marioroy** [comment]
Blessings and Grace. Thanks again for your CI examples.
